---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

This [R Markdown](http://rmarkdown.rstudio.com) Notebook runs code for the tables and figures presented in the paper: "Wired to exit: Exploring the effects of wayfinding affordances in underground facilities using Virtual Reality"

```{r message=FALSE, warning=FALSE}
library(plyr)
library(readr)
library(dplyr)
library(tidyverse)
```

```{r message=FALSE, warning=FALSE}
#Import and merge individual HR data files from the ./raw folder
files <- list.files("raw",full.names=TRUE)
tbl <- sapply(files, read_csv,col_name =c("time", "value"), simplify=FALSE) %>% 
  bind_rows(.id = "id")

tbl$id<-stringr::str_replace(tbl$id, "raw/", "")

```

```{r}
dim(tbl)
names(tbl)
table(tbl$id)
tbl
```
```{r}
#Convert to correct time zone
attr(tbl$time, "tzone") <- "Europe/Helsinki"

#Create new feature for relative time
tbl<- tbl %>% group_by(id) %>% mutate(counter = row_number())

#Assign individual levels
tbl$id = factor(tbl$id, levels = c('user4', 'user5', "user6", "user7",
                                   "user8", "user9",'user10', 'user11', "user12", "user13",
                                   "user14", "user15","user16", "user17","user18","user19", "user20"),
                labels = c(4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20))

```

```{r}
dim(tbl)
tbl
```

```{r}
#Import Physiological & Behavioral indicators
data <- read.delim("~/Desktop/data_BMP/data.tsv")

#Convert date-time
data$StartTime<- strptime(data$StartTime, format="%m.%d.%Y %H.%M.%S")
data$EndTime<- strptime(data$EndTime, format="%m.%d.%Y %H.%M.%S")
```
```{r}
options(dplyr.width =110)
glimpse(data)
```

```{r message=FALSE, warning=FALSE}

# Find the intercept to keep HR data only during gameplay 
user4<- tbl %>% filter(id == "4")

data[ ,1:3] # lookup table
user4 %>% filter(time == "2020-2-10 14:52:56") #start time
user4 %>% filter(time == "2020-2-10 14:58:58") #end time

user5<- tbl %>% filter(id == "5")
user5 %>% filter(time == "2020-2-10 15:16:45")
user5 %>% filter(time == "2020-2-10 15:19:06")          


user6<- tbl %>% filter(id == "6")
user6 %>% filter(time == "2020-2-10 15:37:34")
user6 %>% filter(time == "2020-2-10 15:40:22")          

user7<- tbl %>% filter(id == "7")
user7 %>% filter(time == "2020-2-10 15:57:48")
user7 %>% filter(time == "2020-2-10 15:59:10")          

user8<- tbl %>% filter(id == "8")
user8 %>% filter(time == "2020-2-10 16:23:57")
user8 %>% filter(time == "2020-2-10 16:25:49")          

user9<- tbl %>% filter(id == "9")
user9 %>% filter(time == "2020-2-10 16:47:32")
user9 %>% filter(time == "2020-2-10 16:49:04")          

user10<- tbl %>% filter(id == "10")
user10 %>% filter(time == "2020-2-11 12:26:54")
user10 %>% filter(time == "2020-2-11 12:28:35")          

user11<- tbl %>% filter(id == "11")
user11 %>% filter(time == "2020-2-11 12:52:13")
user11 %>% filter(time == "2020-2-11 12:56:16")          

user12<- tbl %>% filter(id == "12")
user12 %>% filter(time == "2020-2-11 13:20:44")
user12 %>% filter(time == "2020-2-11 13:22:35")          

user13<- tbl %>% filter(id == "13")
user13 %>% filter(time == "2020-2-11 13:43:46")
user13 %>% filter(time == "2020-2-11 13:46:49")          

user14<- tbl %>% filter(id == "14")
user14 %>% filter(time == "2020-2-11 14:07:32")
user14 %>% filter(time == "2020-2-11 14:09:20")          

user15<- tbl %>% filter(id == "15")
user15 %>% filter(time == "2020-2-11 14:47:32")
user15 %>% filter(time == "2020-2-11 14:48:45")          

user16<- tbl %>% filter(id == "16")
user16 %>% filter(time == "2020-2-11 15:11:40")
user16 %>% filter(time == "2020-2-11 15:14:41")          

user17<- tbl %>% filter(id == "17")
user17 %>% filter(time == "2020-2-11 15:40:15")
user17 %>% filter(time == "2020-2-11 15:44:43")          

user18<- tbl %>% filter(id == "18")
user18 %>% filter(time == "2020-2-12 14:38:18")
user18 %>% filter(time == "2020-2-12 14:44:47")

user19<- tbl %>% filter(id == "19")
user19 %>% filter(time == "2020-2-12 15:05:28")
user19 %>% filter(time == "2020-2-12 15:06:28")          

user20<- tbl %>% filter(id == "20")
user20 %>% filter(time == "2020-2-12 15:42:09")
user20 %>% filter(time == "2020-2-12 15:51:27")          


```
```{r}
#Figure 5
#plot HR data. Use intercepts from the previous step as checkpoints and identify the area of gameplay. 

library(gridExtra)
library(ggplot2)
p4<- ggplot(data=user4, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(626,988),colour="#BB0000") +   labs(x = "User1", y = "")
p5 <- ggplot(data=user5, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(448,589),colour="#BB0000") +  labs(x = "User2", y = "")
p6 <- ggplot(data=user6, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(455,623),colour="#BB0000") +  labs(x = "User3", y = "")
p7 <- ggplot(data=user7, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(448,530),colour="#BB0000") +  labs(x = "User4", y = "")
p8 <- ggplot(data=user8, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(552,664),colour="#BB0000") +  labs(x = "User5", y = "")
p9 <- ggplot(data=user9, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(598,690),colour="#BB0000") +  labs(x = "User6", y = "")
p10 <- ggplot(data=user10, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(607,708),colour="#BB0000") +  labs(x = "User7", y = "")
p11 <- ggplot(data=user11, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(532,775),colour="#BB0000") +  labs(x = "User8", y = "")
p12 <- ggplot(data=user12, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(574,685),colour="#BB0000") +  labs(x = "User9", y = "")
p13<- ggplot(data=user13, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(556,739),colour="#BB0000") +  labs(x = "User10", y = "")
p14 <- ggplot(data=user14, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(528,636),colour="#BB0000") +  labs(x = "User11", y = "")
p15 <- ggplot(data=user15, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(660,733),colour="#BB0000") +  labs(x = "User12", y = "")
p16 <- ggplot(data=user16, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(607,788),colour="#BB0000") +  labs(x = "User13", y = "")
p17 <- ggplot(data=user17, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(626,894),colour="#BB0000") +  labs(x = "User14", y = "")
p18 <- ggplot(data=user18, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(569,958),colour="#BB0000") +  labs(x = "User15", y = "")
p19 <- ggplot(data=user19, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(415,475),colour="#BB0000") +  labs(x = "User16", y = "")
p20 <- ggplot(data=user20, aes (x=counter, y=value)) + geom_line() + geom_vline(xintercept = c(480,1038),colour="#BB0000") +  labs(x = "User17", y = "")

grid.arrange(p5,p9,p12,p13,p15,p16,p17,p18,p19,p20, ncol=3,top="Control Group", 
             left="HR")

grid.arrange(p4,p7, p8,p14, p6,p10,p11, ncol=3,top="Experimental Group", bottom="Users", 
             left="HR")

```

```{r}

#Figure 6
#Store the actual HR data between the intercepts for each user.

tsuser4<- user4 %>% filter(counter %in% (626:988))
tsuser5<- user5 %>% filter(counter %in% (448:589))
tsuser6<- user6 %>% filter(counter %in% (455:623))
tsuser7<- user7 %>% filter(counter %in% (448:530))
tsuser8<- user8 %>% filter(counter %in% (552:664))
tsuser9<- user9 %>% filter(counter %in% (598:690))

tsuser10<- user10 %>% filter(counter %in% (607:708))
tsuser11<- user11 %>% filter(counter %in% (532:775))
tsuser12<- user12 %>% filter(counter %in% (574:685))
tsuser13<- user13 %>% filter(counter %in% (556:739))
tsuser14<- user14%>% filter(counter %in% (528:636))
tsuser15<- user15 %>% filter(counter %in% (660:733))
tsuser16<- user16 %>% filter(counter %in% (607:788))
tsuser17<- user17 %>% filter(counter %in% (626:894))
tsuser18<- user18 %>% filter(counter %in% (569:958))
tsuser19<- user19 %>% filter(counter %in% (415:475))
tsuser20<- user20 %>% filter(counter %in% (480:1038))

# Grouping of the stored HR data
experimental <- rbind(tsuser4, tsuser6,tsuser10,tsuser11,tsuser7,tsuser8, tsuser14)
experimental$counter2 <- seq.int(nrow(experimental))

control <- rbind(tsuser5, tsuser9,tsuser12,tsuser13,tsuser15,tsuser16, tsuser17, tsuser18, tsuser19,tsuser20)
control$counter2 <- seq.int(nrow(control))


#Plot data
par(mfrow=c(1,2), mgp=c(2,1,0),mai=c(1,0.4,0.2,0.1),mar = c(4,4,4,2) + 0.1)
plot(experimental$value, type="l",col="green",  ylab ="HR",main= "Experimental Group", xlab ="Relative time",cex.lab = 0.8,cex.axis= 0.7)
plot(control$value, type="l", col="red", main= "Control Group", ylab ="HR", xlab ="Relative time",cex.lab = 0.8,cex.axis= 0.7)
dev.off()
```
```{r message=FALSE, warning=FALSE}

#Table 1
library(MASS)
library(effsize)
library(varhandle)
library(trend)
library(gridExtra)

options(scipen=999)

#Let's drop the dates and make some conversions.
data <- data %>% select(-StartTime, -EndTime)
data$Avg.speed..m.s.<-as.numeric(gsub(",", ".", gsub("\\.", "", data$Avg.speed..m.s.)))

```
```{r}
# Fisher's F-test for categorical data 
set.seed(882)

gender <- table(data$Group, data$Gender) 
print(fisher.test(gender,conf.level = 0.95))

military <- table(data$Group, data$Military.Service.division.) 
print(fisher.test(military,conf.level = 0.95))

# How.often.do.you.park.to.an.underground.parking.space.

parking <- table(data$Group, 
                 data$How.often.do.you.park.to.an.underground.parking.space.) 
print(fisher.test(parking))


# How.often.do.you.play.video.games
games <- table(data$Group, data$How.often.do.you.play.video.games.) 
print(fisher.test(games,alternative='g'))

#How.often.do.you.use.virtual.reality.equipment.
vr <- table(data$Group, data$How.often.do.you.use.virtual.reality.equipment.) 
print(fisher.test(vr))
```

```{r}
# TABLE I. 	CONTINUES DEMOGRAPHIC AND PHYSIOLOGICAL VARIABLES
#Continuous data 

# if F-Test returns p > 0.05 then run t.test with (var.equal = TRUE);
# else F-test returns p < 0.05 (heteroscedasticity) then run (var.equal = FALSE)

#AGE
set.seed(882)
var.test
age <- data$Age
group <- data$Group
t.test(age ~ group,var.equal = TRUE,conf.level=0.95)

#BMI
var.test
data$BMI<-as.numeric(gsub(",", ".", gsub("\\.", "", data$BMI)))
BMI <- data$BMI
var.test
t.test(BMI ~ group, var.equal = TRUE,conf.level=0.95)

#HR 
var.test(control$value, experimental$value)


t.test(control$value, experimental$value, var.equal = FALSE)
t.test(control$value,experimental$value) 

```

```{r}
#TABLE II. 	GAME PERFORMANCE ANALYTICS VARARAIBLES

Ga<- data%>% filter(Group == "A")
Gb<- data%>% filter(Group == "B")

set.seed(882)
#completion time  
comp_a<- Ga$Completion.time..s. 
comp_b<- Gb$Completion.time..s.
var.test(comp_a,comp_b) # F Test 
t.test(comp_a,comp_b,var.equal=T)
t.test(comp_a,comp_b,alternative= 'l',var.equal=T)


#walking distance
walk_a<- Ga$Walk.distance..m.
walk_b<- Gb$Walk.distance..m.
var.test(walk_a,walk_b)
t.test(walk_a,walk_b,var.equal=T)
t.test(walk_a,walk_b,alternative= 'l',var.equal=T)


#speed
speed_a<- Ga$Avg.speed..m.s.
speed_b<- Gb$Avg.speed..m.s.
var.test(speed_a,speed_b)
t.test(speed_a, speed_b, var.equal=F)
t.test(speed_a,speed_b,alternative= 'l',var.equal=F)


#stops
stop_a<- Ga$Number.of.stops
stop_b<- Gb$Number.of.stops
var.test(stop_a,stop_b)
t.test(stop_a, stop_b, var.equal=F)
t.test(stop_a, stop_b,alternative= 'l',var.equal=F)


#rotations
turns_a<- Ga$Number.of.rotations..45.deg.turns.
turns_b<- Gb$Number.of.rotations..45.deg.turns.
var.test(turns_a,turns_b)
t.test(turns_a, turns_b, var.equal=T)
t.test(turns_a, turns_b,alternative= 'l',var.equal=T)

#Ambulance found_Goal
goal_a<- Ga$Ambulance.time
goal_b<- Gb$Ambulance.time
var.test(goal_a,goal_b)
t.test(goal_a, goal_b, var.equal=F)



#Figure 4

par(mfrow=c(2,3), mgp=c(2,1,0),mai=c(0.3,0.4,0.2,0.1))

boxplot(comp_a, comp_b, names = c("CG","EG"),
        ylab ="Compl. time", main= "A", xlab ="Group",cex.lab = 1,cex.axis= 0.7)
boxplot(walk_a, walk_b, names = c("CG","EG"), 
        ylab ="Walk dist.",main= "B", xlab ="Group",cex.lab = 1,cex.axis= 0.7)
boxplot(speed_a, speed_b, names = c("CG","EG"), 
        ylab ="Avr. speed",main= "C", xlab ="Group",cex.lab = 1,cex.axis= 0.7)
boxplot(stop_a, stop_b, names = c("CG","EG"), 
        ylab ="Number of Stops", main= "D",xlab ="Group",cex.lab = 1,cex.axis= 0.7)
boxplot(turns_a, turns_b, names = c("CG","EG"), 
        ylab ="Number of turns", main= "E",xlab ="Group",cex.lab = 1,cex.axis= 0.7)
boxplot(goal_a, goal_b, names = c("CG","EG"), 
        ylab ="Time to Goal", main= "F",xlab ="Group",cex.lab = 1,cex.axis= 0.7)

dev.off()

```
```{r}
######TABLE III. 	PHYSIOLOGICAL TRENDS - Mann-Kendall test for trend
library(trend)
mk.test(experimental$value)
mk.test(control$value)

```

